/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as assestNftSol from "./AssestNFT.sol";
export type { assestNftSol };
import type * as fractionalFactorySol from "./FractionalFactory.sol";
export type { fractionalFactorySol };
